title: Our Menu
description: Delicious recipes with preparation details
domain: menu.benbuckton.com
url: https://menu.benbuckton.com
baseurl: ""

collections:
  recipes:
    output: true
    permalink: /recipes/:name
  ingredients:
    output: true
    permalink: /ingredients/:name

defaults:
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipe-detail"
  - scope:
      path: ""
      type: "ingredients"
    values:
      layout: "ingredient-detail" 