title: Our Menu
description: Delicious recipes with preparation details
baseurl: "/menu-site"
url: "https://yourusername.github.io"

collections:
  recipes:
    output: true
    permalink: /recipes/:name

defaults:
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: "item" 